### PR TITLE
fixed errors for mingw

### PR DESCRIPTION
**Pull request by gittermatt**
made changes to Makefile and src/thread.h to eliminate errors that where generated after "make" command using mingw

### CODE REVIEW

**Comment by sneves** [comment]
What version of MinGW is this failing on?

**Comment by gittermatt** [comment]
I know that it doesn't add support but mingw in my pc (version 4.8) generates error during the make presess that terminates building only argon2.exe and not the libraries, with my changes I'm able to build everything

**Comment by gittermatt** [comment]
sorry, I previously said that the gcc version was 4.8, it is actually 4.9.3

**Comment by sneves** [comment]
OK, I am able to reproduce the `CC=gcc` issue, but not the other ones. In particular, `uintptr_t` is already imported from the `process.h` definitions in every MinGW version I tried (which, granted, was not an exhaustive list).

Could you paste here the errors you were getting when building?

**Comment by gittermatt** [comment]
error

**Comment by gittermatt** [comment]
the error related to the c89 occours when building the test.c file

**Comment by technion** [comment]
@gittermatt Am I correct in that the "test.c" you've referred to is your own test (possibly copied from the README) rather than distributed code? I can't find anything that looks like that line in the distribution's test.c.

I believe a more appropriate solution here would be to fix the example code, or build it specifically, rather than the whole project, using the relevant -std flag.

The CC= fix seems to be agreed on however.

**Comment by gittermatt** [comment]
yes, test.c is the example in the readme and I agree with you, I just wanted to point out the error

**Comment by khovratovich** [comment]
If the example is incorrect, there must be a change for readme.md, not for the thread.c and the makefile.

**Pull request closed without merging**
