### PR TITLE
add support for no threading

### PR DESCRIPTION
**Pull request by sneves**
As suggested by Joseph Richey in #187, this adds support for a situation where threads may not be available for one reason or another.

### CODE REVIEW

**Comment by khovratovich** [comment]
The BENCH setting uses multithreading too. Should not we modify the bench.c code accordingly?

**Comment by sneves** [comment]
The only actual use of threads is in `core.c`. Everywhere else, including `bench.c`, sets the thread number in the parameters, but this will just reflect the number of lanes.

**Comment by khovratovich** [comment]
Why do we have checks failed?

**Comment by sneves** [comment]
Fixed. `CI_FLAGS` was using `CFLAGS` before it was entirely defined.

**Comment by luc-lynx** [comment]
@sneves actually there is no need to leave only `p=1` case if `ARGON2_NO_THREADS` defined as for `p > 2` all the computations can be carried out sequentially in a loop in the `fill_memory_blocks_st` function. I can submit a separate PR if you agree.. :)

**Comment by sneves** [comment]
Isn't this what already happens?

```
#if defined(ARGON2_NO_THREADS)
    return fill_memory_blocks_st(instance);
#else
    return instance->threads == 1 ? fill_memory_blocks_st(instance) : fill_memory_blocks_mt(instance);
#endif
```

When `ARGON2_NO_THREADS` is defined, any parallelism degree goes through `fill_memory_blocks_st`. Otherwise, if `ARGON2_NO_THREADS` is not defined it uses threads as necessary. Did you mean something else?

**Comment by luc-lynx** [comment]
@sneves Oh, I see, you're right.. sorry for misleading you.

**Comment by khovratovich** [comment]
Thanks!

**Pull request merged**
