### PR TITLE
avoid thread creation in p=1 case

### PR DESCRIPTION
**Pull request by luc-lynx**
A pull request for issue #187

### CODE REVIEW

**Comment by luc-lynx** [comment]
There is something wrong with the codecov because Travis builds were successful..

**Comment by sneves** [comment]
Given how simple the main loop is without threads, i.e., 

```
    for (r = 0; r < instance->passes; ++r) {
        for (s = 0; s < ARGON2_SYNC_POINTS; ++s) {
            for (l = 0; l < instance->lanes; ++l) {
                argon2_position_t position = { r, l, (uint8_t)s, 0 };
                fill_segment(instance, position);
            }
        }
    }
    return ARGON2_OK;
```

would it not be cleaner to have one main loop for `threads = 1`, and a separate main loop for `threads > 1`, instead of having a single loop with the conditions inline?

**Comment by SparkDustJoe** [comment]
For performance as well, the fewest branches and tests inside the loop the
better.

**Comment by luc-lynx** [comment]
@sneves sure, thanks for the suggestion. I've updated the PR.

**Pull request merged**
