### PR TITLE
Add options for hash length and bare output to exe

### PR DESCRIPTION
**Pull request by alipha**
I saw on https://github.com/khovratovich/Argon2/issues/21 that it was requested to be able to have the argon2 utility be able to output only the hexadecimal of the hash, and I thought that was useful, so I implemented that (-r) along with outputting only your $argon2i$... encoded string (-e). I also thought it might be nice to generate different output hash lengths, so I added that too (-h length). A max length of 1024 seems a little large, but having a max at all seems a bit arbitrary.

### CODE REVIEW

**Comment by ranisalt** [comment]
While you're at it, mind that you need not (and IMHO should not) to hardcode an ENCODED_LEN, as it can be dynamically calculated, [check this function](https://github.com/ranisalt/node-argon2/blob/e804fed9483173d0a2d04c88430d81f7bc9e54ac/src/argon2_node.cpp#L20-L41).

As of today, the utility only permits salts up to 16 bytes and your solution keeps an upper limit, although increasing it.

**Comment by khovratovich** [comment]
Could one of you bring the encoded calculation function to the code? Then we can approve this PR.

**Comment by ranisalt** [comment]
Gonna do it as soon as I get home.

**Comment by khovratovich** [comment]
Please resolve the conflicts.

**Comment by daniel-dinu** [comment]
@alipha please resolve the conflicts, else your pull request will be closed

**Comment by alipha** [comment]
My apologies for the lack of attention of this pull request.

**Pull request closed without merging**
