### PR TITLE
Address issue #74

### PR DESCRIPTION
**Pull request by sneves**
This is my proposed resolution to #74. I'm making this a pull request so it gets feedback.

 - Error codes which do not represent success are now negative.
 - There is no longer an `ARGON2_ERROR_CODES_LENGTH` member that can silently change between API versions.

The only question that remains, in my view, is whether to remove the error codes from the public `argon2.h` header and make them internal (or maybe in an independent public header, e.g., `argon2-error.h`). I lean against it, since it might be useful for a user to be able to discriminate between error types, but either way is fine for me.

### CODE REVIEW

**Comment by khovratovich** [comment]
I like the idea, and I am also in favor of leaving the error codes in `argon2.h`

**Comment by ranisalt** [comment]
> Error codes which do not represent success are now negative.

Can you explain why? Please mind that it's an enum and users should never directly compare the return code to a number (e.g. `result < 0`)  but rather compare to a code (e.g. `result != ARGON2_OK`).

**Comment by SparkDustJoe** [comment]
In most other schemes I've used, there is usually a return value
representative of the number of bytes processed or zero for fail... OR...
Zero for success and some 0x80000000 number representative of a specific
error.  Never see mixed positive and negative numbers and zero equals
success (I'm not counting string comparisons).

**Comment by ranisalt** [comment]
Please, it's an enum, although in low level `ARGON2_OK` equals 0 it is NOT semantically the same. It's not like "the function returns a positive number" but rather it returns a symbol, represented by a number with no direct meaning.  I don't even understand why there are values since enum values should be assigned automatically.

**Comment by sneves** [comment]
It is a common idiom in C that functions return `0` for success and `< 0` for errors. This is not the case everywhere; on Windows, it is common that nonzero represents success, and zero is an error. But on Unix this seems to be the norm. `0` is also the default C success value, as shown by the definition of the `main` function, even though `EXIT_SUCCESS` also exists and is not required to equal `0`.

Enums in C are essentially just integers. Unlike in C++, where you can have strong type-safe enums, here they're essentially no better than a long list of `#define`s. Also, note that the return values of all functions are `int`, not `argon2_error_code`. 

Anyway, the point is that you can continue to use enums just the way you did before; nothing's changed about that. The only change is that a common C idiom is supported without breaking things.

**Comment by ranisalt** [comment]
Oh, fine, I do not have the background of a C programmer.

**Comment by khovratovich** [comment]
Please feel free to resolve the conflicts and merge.

**Pull request merged**
